

include: package:lints/recommended.yaml

# Uncomment the following section to specify additional rules.

# linter:
#   rules:
#     - camel_case_types
formatter:
  page_width: 120
  
analyzer: 
  exclude:
  # exclude warnings in .g.dart
    - "test/generated/**"
    - "**/*.g.dart"


  plugins:
 # enable riverpod_lint
    - custom_lint
#   exclude:
#     - path/to/excluded/files/**

  errors:
    #fix json_serializable and freezed lint issues
    invalid_annotation_target: ignore
#code analysis
dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml
  
