name: conversational_agent_client
description: A Dart Client for conversational agent restApi
version: 1.4.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: 3.7.0

# Add regular dependencies here.
dependencies:
  dio: 5.7.0
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  logger: 2.5.0
  riverpod: 2.6.1
  riverpod_annotation: 2.6.1
 

dev_dependencies:
  build_runner: 2.4.14
  custom_lint: 0.7.1
  freezed: 2.5.8
  json_serializable: 6.9.2
  lints: 5.1.1
  riverpod_generator: 2.6.4
  riverpod_lint: 2.6.4
  test: 1.25.14
    #code analyzer
  dart_code_metrics_presets: 2.20.0
