name: conversational_agent_client
description: A Dart Client for conversational agent restApi
version: 1.3.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  dio: 5.7.0
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  logger: 2.4.0
  riverpod: 2.6.1
  riverpod_annotation: 2.6.1
 

dev_dependencies:
  build_runner: 2.4.13
  custom_lint: 0.6.8
  freezed: 2.5.7
  json_serializable: 6.8.0
  lints: 4.0.0
  riverpod_generator: 2.6.1
  riverpod_lint: 2.6.1
  test: 1.25.8
    #code analyzer
  dart_code_metrics_presets: 2.18.0
