name: new_geiger_toolbox
description: A new single code repository used for developing new tools within the GeigerToolbox Application.
publish_to: "none"

version: 0.0.1

environment:
  #Dart SDK version that flutter project is compatible with
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 

dev_dependencies:
  # for managing multiple repo (monoreop)
  melos: 6.1.0
  #  to automatcally lint commit-message
  commitlint_cli: 0.7.1
  # to manage commit-message git hooks 
  husky: 0.1.7

