include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
  # exclude warnings in .g.dart
    - "test/generated/**"
    - "**/*.g.dart"
  errors:
    invalid_annotation_target: ignore

formatter:
  page_width: 120
