name: core_ui
description: "A design system for geiger toolbox"
version: 2.0.0
homepage: "cyber-geiger.com"

environment:
  sdk: 3.5.4
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: 3.4.1
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.4
  gap: 3.0.1
  json_annotation: 4.9.0
  shimmer: 3.0.0
  wolt_modal_sheet: 0.9.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  build_runner: 2.4.13
  freezed: 2.5.7
  json_serializable: 6.8.0
  flutter_gen_runner: 5.8.0
  golden_toolkit: 0.15.0

#for auto generating referece class for assets
flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
    integrations:
  fonts:
    exclude:
      - assets/fonts/Roboto-Regular.ttf
    outputs:
      package_parameter_enabled: true
  

flutter:
  assets:
    - assets/images/

  fonts:
    - family: ttNorms
      fonts:
        - asset: assets/fonts/TT-Norms-Fonts/TTNorms-Regular.otf
        - asset: assets/fonts/TT-Norms-Fonts/TTNorms-Bold.otf
    - family: geiger_icons
      fonts:
        - asset: assets/fonts/geiger_icons/geiger_icons.ttf
    #used for Golden Image tests
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  uses-material-design: true
  
