// ignore_for_file: public_member_api_docs, sort_constructors_first
///Base class fro all cliend-side errors that can be generated by the app
sealed class AppException implements Exception {
  final String code;
  final String message;
  const AppException({required this.code, required this.message});

  @override
  String toString() => 'AppException(code: $code, message: $message)';
}

//
class UserNotFoundException extends AppException {
  UserNotFoundException()
      : super(
            code: 'user-not-found', message: "User profile has not be created");
}

class CachedNewsFeedException extends AppException {
  CachedNewsFeedException()
      : super(
            code: 'fail-read-newsfeed-cache',
            message: "Fail to retrived cached news data");
}

class CachedNewsFeedStoreException extends AppException {
  CachedNewsFeedStoreException()
      : super(code: 'fail-cache-newsfeed', message: "Fail to cache news data");
}

class DeleteCachedNewsFeedStoreException extends AppException {
  DeleteCachedNewsFeedStoreException({this.error, this.stack})
      : super(
            code: error ?? 'fail-delete-cache-newsList',
            message: stack ?? "Fail to delete news object from cache");

  final String? error;
  final String? stack;
}

class AddTodoTaskRepositryException extends AppException {
  AddTodoTaskRepositryException()
      : super(
            code: 'fail-add-todo-cache',
            message: "Fail to add todo task to cache");
}

class FetchTodoTaskRepositryException extends AppException {
  FetchTodoTaskRepositryException()
      : super(
            code: 'fail-to-get-todo-cache',
            message: "Fail to retrive todo task to cache");
}

class RemoveTodoTaskRepositryException extends AppException {
  RemoveTodoTaskRepositryException()
      : super(
            code: 'fail-remove-todo-cache',
            message: "Fail to remove todo task to cache");
}

class DataBaseException extends AppException {
  DataBaseException({this.error, this.stack})
      : super(
            code: error ?? "database-exception",
            message: stack ?? "Data Exception");

  final String? error;
  final String? stack;
}
