
include: package:flutter_lints/flutter.yaml

linter:
  
  # producing the lint.
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
formatter:
  page_width: 120

analyzer: 
  exclude:
  # exclude warnings in .g.dart
    - "test/generated/**"
    - "**/*.g.dart"
    - lib/main_*.dart

  plugins: 
    # enable riverpod_lint
    - custom_lint

 
  errors:
    #fix json_serializable and freezed lint issues
    invalid_annotation_target: ignore


        
  
