name: geiger_toolbox
description: "A cybersecurity risk management tool designed for SMEs and their lay staff, focusing on improving cybersecurity awareness, providing personalized risk assessments, and reducing vulnerabilities."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: 3.5.4

dependencies:
  flutter:
    sdk: flutter
  core_ui: 2.0.0
  conversational_agent_client: 1.2.1
  cupertino_icons: 1.0.8
  go_router: 14.6.0
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  custom_lint: 0.7.0
  logger: 2.4.0
  freezed_annotation: 2.4.4
  carousel_slider_plus: 7.0.2
  sembast: 3.7.5+2
  sembast_web: 2.4.0+4
  path_provider: 2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  build_runner: 2.4.13
  riverpod_generator: 2.6.3
  riverpod_lint: 2.6.3
  freezed: 2.5.7

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

