name: geiger_toolbox
description: "A cybersecurity risk management tool designed for SMEs and their lay staff, focusing on improving cybersecurity awareness, providing personalized risk assessments, and reducing vulnerabilities."

publish_to: 'none' 

version: 1.0.0+3

environment:
  sdk: 3.6.0

dependencies:
  flutter:
    sdk: flutter
  core_ui: 1.3.1
  conversational_agent_client: 1.4.0
  perplexity_search: 1.1.0
  cupertino_icons: 1.0.8
  go_router: 14.6.0
  flutter_riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  custom_lint: 0.7.0
  freezed_annotation: 2.4.4
  carousel_slider_plus: 7.0.2

   # Drift and friends
  drift: 2.21.0
  drift_dev: 2.21.2
  path_provider: 2.1.5
  path: 1.9.0
  sqlite3_flutter_libs: 0.5.26
  sqlite3: 2.4.7

  #other packages

  json_annotation: 4.9.0
  package_info_plus: 8.1.1
  
  shared_preferences: 2.3.3
  intl: 0.19.0
  # error monitor
  sentry_flutter: 8.10.1
  # send feedback
  feedback: 3.1.0
  # feedback collection
  feedback_sentry: 3.1.0
  # app analytics
  firebase_analytics: 11.3.3
  firebase_core: 3.6.0
  # mixpanel
  mixpanel_flutter: 2.3.3
  device_info_plus: 11.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  build_runner: 2.4.13
  riverpod_generator: 2.6.3
  riverpod_lint: 2.6.3
  freezed: 2.5.7
  json_serializable: 6.9.0
  #check for memory leaks during testing
  leak_tracker_flutter_testing: 3.0.8

  flutter_launcher_icons: 0.14.1
  flutter_native_splash: 2.4.3
  flutter_flavorizr: 2.2.3
  sentry_dart_plugin: 2.1.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
 # assets:
   # - assets/

