name: perplexity_search
description: A starting point for Dart libraries or applications.
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: 3.6.0

# Add regular dependencies here.
dependencies:
  dio: 5.7.0
  riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  logger: 2.5.0

dev_dependencies:
  build_runner: 2.4.14
  custom_lint: 0.7.0
  freezed: 2.5.7
  json_serializable: 6.8.0
  riverpod_generator: 2.6.3
  riverpod_lint: 2.6.3
  lints: 5.1.1
  test: 1.25.14
