on:
    pull_request:
      branches: [ "main" ]
      types: [opened, synchronize]
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
          - name: Flutter Checkout@3
            uses: actions/checkout@v3
            with:
                fetch-depth: 0

          - name: Use Flutter Action@v2.10
            uses: subosito/flutter-action@v2.10.0
      
          - name: Get Flutter Dependencies
            run: flutter pub get
  
          - name: Validate PR Commits
            run: VERBOSE=true dart run commitlint_cli --from=${{ github.event.pull_request.head.sha}}~${{ github.event.pull_request.commits}} --to=${{ github.event.pull_request.head.sha}} -- config lib/commitlint.yaml